name: Update Gist

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run update script
        env:
          GIST_UPDATE_TOKEN: ${{ secrets.GIST_UPDATE_TOKEN }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: node ./auth/gist.js 