name: Test Python

on:
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Replace '3.x' with a specific version if needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv sose
          source sose/bin/activate
          pip install --upgrade pip
          # Add any required dependencies if necessary (e.g., pip install -r requirements.txt)

      # Step 4: Run the Python script
      - name: Run Python script
        run: |
          source sose/bin/activate
          python scripts/01.py
